version: '2'
services:
    erebus:
        container_name: erebus
        build: .

    reverse-proxy:
        container_name: reverse-proxy
        image: nginx
        ports:
         - "9090:8080"
        volumes:
         - ./nginx.conf:/etc/nginx/conf.d/default.conf